name: Go Auto Release CI

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.3

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -o passmake -ldflags "-s -w" src/main.go

      - name: Create Release
        run: |
          spliced_sha=$(echo ${{ github.sha }} | cut -c1-7)
          response=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/GustavoWidman/passmake/releases \
          --data '{
            "tag_name": "AR-'$spliced_sha'",
            "body": "This is an Automatic Release triggered by a push to the main branch. It references the commit ${{ github.sha }}."
          }')
          echo $response
          id=$(echo $response | jq -r '.id')
          echo "Release ID: $id"
          echo "$id" > release_id

      - name: Upload Asset
        run: |
          id=$(cat release_id)
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @passmake \
          https://uploads.github.com/repos/GustavoWidman/passmake/releases/$id/assets?name=passmake

      - name: Cleanup
        run: |
          rm passmake
          rm release_id
